<?php

/*
 * Do not edit this file, but create a similair file in the config subfolder production with the config elements
 * you wish to override. The items you will not define in your custom config file will use the below defaults
 */

return [
    'emailparser' => [
        'fallback_mail'      => 'admin@isp.local',
        'use_bounce_method'  => false,
        'notify_on_warnings' => true,
        'imap' => [
            'host' => 'mail.server.local',
            'port' => '993',
            'ssl' => true,
            'username' => 'abuse@isp.local',
            'password' => ''
        ]
    ],

    'notifications' => [
        'enabled'        => true,
        'info_interval'  => '90 days',
        'abuse_interval' => '0 minutes',
        'min_lastseen'   => '14 days',
        'from_address'   => 'abuse@isp.local',
        'from_name'      => 'ISP Abusedesk',
        'bcc_enabled'    => false,
        'bcc_address'    => 'management@isp.local',
    ],
];
